repos:
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
    - id: terraform_fmt
      verbose: true
      args:
        - --args=-recursive
    - id: terraform_validate
      verbose: true    
    - id: terraform_docs
      verbose: true
      args:
        - --args=--output-file README.md